version: '3.9'
services:
  db:
    image: postgres
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=2277
      - POSTGRES_DB=postgres
  web:
    restart: always
    build: .
    command: uvicorn main:app --reload
    volumes:
      - .:/usr/src/ww2
    ports:
      - 8004:8004
    environment:
      - DATABASE_URL=postgresql://postgres:2277@db:5432/postgres
    depends_on:
      - db

