"""irst migration

Revision ID: 8db7f461ffe1
Revises: 
Create Date: 2022-04-28 17:16:45.511439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8db7f461ffe1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Comments_Photo_owner', table_name='Comments')
    op.drop_index('ix_Comments_comment_owner', table_name='Comments')
    op.drop_index('ix_Comments_id', table_name='Comments')
    op.drop_table('Comments')
    op.drop_index('ix_Photos_id', table_name='Photos')
    op.drop_index('ix_Photos_photo_file', table_name='Photos')
    op.drop_index('ix_Photos_photo_owner', table_name='Photos')
    op.drop_table('Photos')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key')
    )
    op.create_table('Photos',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Photos_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('photo_file', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('photo_dis', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('photo_owner', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Photos_pkey')
    )
    op.create_index('ix_Photos_photo_owner', 'Photos', ['photo_owner'], unique=False)
    op.create_index('ix_Photos_photo_file', 'Photos', ['photo_file'], unique=False)
    op.create_index('ix_Photos_id', 'Photos', ['id'], unique=False)
    op.create_table('Comments',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Comments_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('comment', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('comment_owner', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Photo_owner', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Comments_pkey')
    )
    op.create_index('ix_Comments_id', 'Comments', ['id'], unique=False)
    op.create_index('ix_Comments_comment_owner', 'Comments', ['comment_owner'], unique=False)
    op.create_index('ix_Comments_Photo_owner', 'Comments', ['Photo_owner'], unique=False)
    # ### end Alembic commands ###
